services:
  ansible:
    container_name: ansible
    image: rranzan2001/cansible
    restart: unless-stopped
    command: tail -f /dev/null
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - ./deploy.yml:/root/deploy.yml
    tty: true

  jenkins:
    container_name: jenkins
    image: rranzan2001/djentle
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    driver: local
